---
- hosts: 172.31.17.123
  become: yes
  tasks:
  - name: execute linux directly
    command: hostname -f 
    register: myresult

  - name: i want to display my first task result
    debug: 
      msg: "{{myresult}}"
