---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i want to install webservers on ubuntu nodes
    apt:
     name: apache2
     state: present
    when: ansible_os_family =="Debian"

  - name: i want to start webservers on ubuntu nodes
    service:
     name: apache2
     state: started
    when: ansible_os_family =="Debian"

  - name: i want to install webservers on RedHat nodes
    yum:
     name: httpd
     state: present
    when: ansible_os_family =="RedHat"

  - name: i want to start webservers on RedHat nodes
    service: 
     name: httpd
     state: started
    when: ansible_os_family =="RedHat"